### ISSUE TITLE
Fail to build with ffmpeg 5.0

### ISSUE THREAD

**Issue by marillat** [Emanem/qpsnr#3]
Deprecated functions() introduced in ffmpeg 4 have been removed in ffmpeg 5
and thus qpsnr doesn't build.
```
g++ -W -Wall -ggdb -O2 -D_REENTRANT -pthread -D__STDC_LIMIT_MACROS=1 -D__STDC_CONSTANT_MACROS=1 -D__STDC_FORMAT_MACROS==1 -std=gnu++98 -D_GNU_SOURCE -Wl,-z,relro src/settings.cpp -c -o obj/settings.o
src/qav.cpp: In constructor 'qav::qvideo::qvideo(const char*, int, int)':
src/qav.cpp:46:67: error: 'AVStream' {aka 'struct AVStream'} has no member named 'codec'
   46 |                 if (AVMEDIA_TYPE_VIDEO == pFormatCtx->streams[i]->codec->codec_type) {
      |                                                                   ^~~~~
src/qav.cpp:56:53: error: 'AVStream' {aka 'struct AVStream'} has no member named 'codec'
   56 |         pCodecCtx=pFormatCtx->streams[videoStream]->codec;
      |                                                     ^~~~~
src/qav.cpp:57:36: error: invalid conversion from 'const AVCodec*' to 'AVCodec*' [-fpermissive]
   57 |         pCodec=avcodec_find_decoder(pCodecCtx->codec_id);
      |                ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
      |                                    |
      |                                    const AVCodec*
src/qav.cpp: In member function 'bool qav::qvideo::get_frame(std::vector<unsigned char>&, int*, bool)':
src/qav.cpp:105:20: error: 'avpicture_get_size' was not declared in this scope
  105 |         out.resize(avpicture_get_size(AV_PIX_FMT_RGB24, out_width, out_height));
      |                    ^~~~~~~~~~~~~~~~~~
src/qav.cpp:108:23: warning: 'void av_init_packet(AVPacket*)' is deprecated [-Wdeprecated-declarations]
  108 |         av_init_packet(&packet);
      |         ~~~~~~~~~~~~~~^~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:45,
                 from src/qav.h:25,
                 from src/qav.cpp:20:
/usr/include/x86_64-linux-gnu/libavcodec/packet.h:506:6: note: declared here
  506 | void av_init_packet(AVPacket *pkt);
      |      ^~~~~~~~~~~~~~
src/qav.cpp:113:32: error: 'avcodec_decode_video2' was not declared in this scope; did you mean 'avcodec_decode_subtitle2'?
  113 |                         if(0 > avcodec_decode_video2(pCodecCtx, pFrame, &frameFinished, &packet))
      |                                ^~~~~~~~~~~~~~~~~~~~~
      |                                avcodec_decode_subtitle2
src/qav.cpp:120:41: error: 'AVPicture' was not declared in this scope; did you mean 'AVPictureType'?
  120 |                                         AVPicture picRGB;
      |                                         ^~~~~~~~~
      |                                         AVPictureType
src/qav.cpp:122:67: error: expected primary-expression before ')' token
  122 |                                         avpicture_fill((AVPicture*)&picRGB, (unsigned char*)&out[0], AV_PIX_FMT_RGB24, out_width, out_height);
      |                                                                   ^
src/qav.cpp:122:69: error: 'picRGB' was not declared in this scope
  122 |                                         avpicture_fill((AVPicture*)&picRGB, (unsigned char*)&out[0], AV_PIX_FMT_RGB24, out_width, out_height);
      |                                                                     ^~~~~~
src/qav.cpp:122:41: error: 'avpicture_fill' was not declared in this scope
  122 |                                         avpicture_fill((AVPicture*)&picRGB, (unsigned char*)&out[0], AV_PIX_FMT_RGB24, out_width, out_height);
      |                                         ^~~~~~~~~~~~~~
src/qav.cpp:130:17: error: 'av_free_packet' was not declared in this scope; did you mean 'av_new_packet'?
  130 |                 av_free_packet(&packet);
      |                 ^~~~~~~~~~~~~~
      |                 av_new_packet
make[1]: *** [Makefile:18: obj/qav.o] Error 1
make[1]: *** Waiting for unfinished jobs....
src/main.cpp: In function 'int main(int, char**)':
src/main.cpp:295:17: error: 'av_register_all' was not declared in this scope
  295 |                 av_register_all();
      |                 ^~~~~~~~~~~~~~~
make[1]: *** [Makefile:26: obj/main.o] Error 1
```
